---
version: "2.0"

services:
  web:
    image: user994455/xmrig:0.3
    env:
      - USER=88z2xaJaRPVc5VXtE3CArxeAkqSQV8aA4EhswR8pqfY3CghQfaD7nYsLvmcnXuHj1TYDeJaGvyyyW9XyX6ka7BLzQ7ypmqJ
      - PASS=pass
      - URL=pool.supportxmr.com:443 --tls
      - DEBUG=true
    expose:
      - port: 22000
        as: 22000
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 2Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 5000

deployment:
  web:
    dcloud:
      profile: web
      count: 2
